library(SGP)
library(plyr)
library(data.table)

CO_MATH <- Colorado_Data_LONG_2016[CONTENT_AREA %in% c("MATHEMATICS", "ALGEBRA_I", "ALGEBRA_II", "GEOMETRY", "INTEGRATED_MATH_1", "INTEGRATED_MATH_2", "INTEGRATED_MATH_3")]

math.prog <- courseProgressionSGP(CO_MATH, lag.direction="BACKWARD", year='2016')

math.prog$BACKWARD[['2016']]$ALGEBRA_I.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.06"]$COUNT) # 2227 -- Singular design matrix
sum(math.prog$BACKWARD[['2016']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 8020
sum(math.prog$BACKWARD[['2016']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 22057

math.prog$BACKWARD[['2016']]$ALGEBRA_II.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)  # 1057
sum(math.prog$BACKWARD[['2016']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT) # 558

math.prog$BACKWARD[['2016']]$GEOMETRY.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 827
sum(math.prog$BACKWARD[['2016']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 1786
sum(math.prog$BACKWARD[['2016']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)   # 6766
sum(math.prog$BACKWARD[['2016']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT)  # 0

math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.06"]$COUNT) # 123
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 1246
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 6837
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="GEOMETRY.CT"]$COUNT)    # 16
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)   # 89
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_II.CT"]$COUNT)  # 0

math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_2.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 17
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 438
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_1.CT"]$COUNT) # 750

math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_3.CT[COUNT>500]
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 16
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="ALGEBRA_I.CT"]$COUNT)   # 32
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_1.CT"]$COUNT) # 43
sum(math.prog$BACKWARD[['2016']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="INTEGRATED_MATH_2.CT"]$COUNT) # 45
