library(SGP)
library(plyr)
library(data.table)
source('/media/Data/Dropbox/Application_Projects/EOC Course progressions/courseProgressionSGP.R', chdir = TRUE)

Colorado_Data_LONG <- as.data.table(subset(rbindlist(list(Colorado_SGP@Data, Colorado_Data_LONG_2015), fill=TRUE), 
	VALID_CASE=="VALID_CASE", select=c("ID", "YEAR", "CONTENT_AREA", "GRADE", "VALID_CASE")))

CO_MATH <- Colorado_Data_LONG[CONTENT_AREA %in% c("MATHEMATICS", "ALGEBRA_I", "ALGEBRA_II", "GEOMETRY", "INTEGRATED_MATH_1", "INTEGRATED_MATH_2", "INTEGRATED_MATH_3")]
CO_MATH[which(CONTENT_AREA %in% c("ALGEBRA_I", "ALGEBRA_II", "GEOMETRY", "INTEGRATED_MATH_1", "INTEGRATED_MATH_2", "INTEGRATED_MATH_3")), GRADE := "EOCT"]
table(CO_MATH$GRADE)

math.prog <- courseProgressionSGP(CO_MATH, lag.direction.argument="BACKWARD", year='2015')

##  Not enough 2014 NAs to make skipped year progressions in ANY subject.  E.g.:
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]$COUNT) # 1005
math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]


math.prog$BACKWARD[['2015']]$ALGEBRA_I.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.06"]$COUNT) # 1692 - Singular design matrix\n"
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 10345
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 22015
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_I.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 4626 
# ::  10th grade = 148

math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 1!
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 1746 - Singular design matrix\n"
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 9555
sum(math.prog$BACKWARD[['2015']]$ALGEBRA_II.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.10"]$COUNT) # 9586

math.prog$BACKWARD[['2015']]$GEOMETRY.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 1800 - Singular design matrix\n"
sum(math.prog$BACKWARD[['2015']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 8432
sum(math.prog$BACKWARD[['2015']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 13719
sum(math.prog$BACKWARD[['2015']]$GEOMETRY.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.10"]$COUNT) # 3824

math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.06"]$COUNT) # 99
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.07"]$COUNT) # 1232
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 7484
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 1075
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_1.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.10"]$COUNT) # 22

math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_2.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 1619
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 5299
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_2.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.10"]$COUNT) # 1107

math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_3.CT[COUNT>500]
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.08"]$COUNT) # 133
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.09"]$COUNT) # 1404
sum(math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_3.CT[CONTENT_AREA_by_GRADE_PRIOR_YEAR.1=="MATHEMATICS.10"]$COUNT) # 3887

math.prog$BACKWARD[['2015']]$INTEGRATED_MATH_3.CT[is.na(CONTENT_AREA_by_GRADE_PRIOR_YEAR.1)]