################################################################################
###                                                                          ###
###     Configurations for STRAIGHT (skip-year) Math projections in 2019     ###
###                                                                          ###
################################################################################

MATHEMATICS_2019.config <- list(
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS"),
        sgp.panel.years=c("2017", "2019"),
        sgp.baseline.panel.years=c("2017", "2019"),
        sgp.grade.sequences=list(c("3", "5")),
        sgp.baseline.grade.sequences=list(c("3", "5")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("3")),
        sgp.projection.sequence="MATHEMATICS_GRADE_3"),
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.panel.years=c("2016", "2017", "2019"),
        sgp.panel.years=c("2016", "2017", "2019"),
        sgp.grade.sequences=list(c("3", "4", "6")),
        sgp.baseline.grade.sequences=list(c("3", "4", "6")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("4")),
        sgp.projection.sequence="MATHEMATICS_GRADE_4"),
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.panel.years=c("2016", "2017", "2019"),
        sgp.panel.years=c("2016", "2017", "2019"),
        sgp.grade.sequences=list(c("4", "5", "7")),
        sgp.baseline.grade.sequences=list(c("4", "5", "7")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("5")),
        sgp.projection.sequence="MATHEMATICS_GRADE_5"),
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS"),
        sgp.baseline.panel.years=c("2016", "2017", "2019"),
        sgp.panel.years=c("2016", "2017", "2019"),
        sgp.grade.sequences=list(c("5", "6", "8")),
        sgp.baseline.grade.sequences=list(c("5", "6", "8")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("6")),
        sgp.projection.sequence="MATHEMATICS_GRADE_6"),
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_9"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_9"),
        sgp.baseline.panel.years=c("2016", "2017", "2019"),
        sgp.panel.years=c("2016", "2017", "2019"),
        sgp.grade.sequences=list(c("6", "7", "9")),
        sgp.baseline.grade.sequences=list(c("6", "7", "9")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("7")),
        sgp.projection.sequence="MATHEMATICS_GRADE_7"),
    MATHEMATICS.2019 = list(
        sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_10"),
        sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_10"),
        sgp.baseline.panel.years=c("2016", "2017", "2019"),
        sgp.panel.years=c("2016", "2017", "2019"),
        sgp.grade.sequences=list(c("7", "8", "10")),
        sgp.baseline.grade.sequences=list(c("7", "8", "10")),
        sgp.projection.baseline.content.areas=c("MATHEMATICS"),
        sgp.projection.baseline.panel.years=c("2019"),
        sgp.projection.baseline.grade.sequences=list(c("8")),
        sgp.projection.sequence="MATHEMATICS_GRADE_8")#,
    # MATHEMATICS.2019 = list( # Can't project to MATHEMATICS_SAT, so GRADE 8 is the end of the line.
    #     sgp.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_10"),
    #     sgp.baseline.content.areas=c("MATHEMATICS", "MATHEMATICS", "MATHEMATICS_PSAT_10"),
    #     sgp.baseline.panel.years=c("2016", "2017", "2019"),
    #     sgp.panel.years=c("2016", "2017", "2019"),
    #     sgp.grade.sequences=list(c("7", "8", "10")),
    #     sgp.baseline.grade.sequences=list(c("7", "8", "10")),
    #     sgp.projection.baseline.content.areas=c("MATHEMATICS"),
    #     sgp.projection.baseline.panel.years=c("2019"),
    #     sgp.projection.baseline.grade.sequences=list(c("9")),
    #     sgp.projection.sequence="MATHEMATICS_GRADE_9")
)
